In [19]:
# 1. Import the numpy package under the name np
import numpy as np

In [20]:
# 2. Print the numpy version and the configuration
np.__version__
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE4

In [21]:
# 3. Create an array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
# 4. Create an array of 10 zeros where the fifth element value is set to 1
X=np.zeros(10)
X[4]=1
print(X)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [23]:
# 5. Create an array with values ranging from 10 to 49 (inclusive) and reverse it
Y=np.arange(10, 50)
np.flip(Y)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [24]:
# 6. Find indices of non-zero elements from [1, 2, 0, 0, 4, 0]
np.nonzero([1, 2, 0, 0, 4, 0])

(array([0, 1, 4]),)

In [25]:
# 7. Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
# 8. Create a 3x3x3 array with random values
np.random.random((3, 3, 3))

array([[[0.54082134, 0.75031713, 0.90168277],
        [0.47552285, 0.46917436, 0.07806539],
        [0.75278034, 0.34627498, 0.93832191]],

       [[0.01966449, 0.149698  , 0.94345671],
        [0.35885414, 0.44665076, 0.43281304],
        [0.15957744, 0.33718493, 0.62651518]],

       [[0.3169885 , 0.50993419, 0.05735843],
        [0.05250211, 0.56944797, 0.65435771],
        [0.71841452, 0.95898237, 0.56413972]]])

In [27]:
# 9. Create an array of all the even numbers from 30 to 70 (inclusive)
np.arange(30,71,2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [28]:
# 10. Generate 10x10 array with random integers between 0 to 4 (inclusive) and find the minimum and maximum values
A=np.random.randint(0, 5, (10,10))
print(A.min(),A.max())

0 4


In [29]:
# 11. Create a 5x5 matrix with values 1, 2, 3, 4 just below the diagonal
np.diag([1, 2, 3, 4],-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [30]:
# 12. Create an array with values ranging from 20 to 39 (inclusive). Calculate the square root of elements in it.
np.sqrt(np.arange(20,40))

array([4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ])

In [31]:
# 13. Transpose the given array [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
np.transpose([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [32]:
# 14. Inverse the given array [[3, 4], [5, 6]]
np.linalg.inv([[3, 4], [5, 6]])

array([[-3. ,  2. ],
       [ 2.5, -1.5]])

In [33]:
# 15. Concatenate two given arrays by columnwise (specify axis = 1)
c = np.array([[1, 2],[3, 4]])
d = np.array([[5, 6],[7, 8]])
np.concatenate((c,d),1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [34]:
# 16. Transpose the given arrays and concatenate by columnwise (specify axis = 1)
a = np.array([[1,2],[3,4]])
d = np.array([[5,6],[7,8]])
np.concatenate((np.transpose(a),np.transpose(d)),1)

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [35]:
# 17. For a given array, print second and third column
a = np.array([[2, 4, 6, 8, 10], 
              [3, 6, 9, 12, 15], 
              [4, 8, 12, 16, 20]])
print(a[:,[1,2]])

[[ 4  6]
 [ 6  9]
 [ 8 12]]


In [36]:
# 18. For a given array, print the values of the second and third rows from the second column.
a = np.array([[10, 11, 12, 13, 14],
               [15, 16, 17, 18, 19],
               [20, 21, 22, 23, 24],
               [25, 26, 27, 28, 29],
               [30, 31, 32, 33, 34]])
print(a[1:3,1])

[16 21]


In [37]:
# 19. For a given array perform the following:
# 1. Calculate mean row wise and column wise by specifying respective axis
# 2. What is the average value of array
array = np.array([[2, 4, 6, 8, 10], 
                  [3, 6, 9, 12, 15], 
                  [4, 8, 12, 16, 20]])
print(np.mean(array,axis = 0), np.mean(array,axis = 1), np.mean(array))

[ 3.  6.  9. 12. 15.] [ 6.  9. 12.] 9.0


In [38]:
# 20. For a given array, get the slice of the first row from all the 3 matrices and print them.
a3 = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]], 
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]], 
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])
print(a3[0,:,:])

[[10 11 12]
 [13 14 15]
 [16 17 18]]


Part 2

In [39]:
# 1. For the given array, display the elements which are greater than 20
a = np.arange(36)
print("Values bigger than 20 =", a[a>20])

Values bigger than 20 = [21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]


In [40]:
# 2. Create an array of 5 evenly spaced values from 0 to 20
np.arange(0,21,5)

array([ 0,  5, 10, 15, 20])

In [41]:
# 3. Create an array with values ranging from 0 to 5 (inclusive) and reshape the array with 2 rows and 3 columns
np.arange(0,6)

array([0, 1, 2, 3, 4, 5])

In [42]:
# 4. For given 2-D arrays, perform vertical and horizontal stack
a = np.array([[9, 8],
              [6, 5]]) 

b = np.array([[4, 7],
              [3, 2]])

np.vstack((a,b))
np.hstack((a,b))

array([[9, 8, 4, 7],
       [6, 5, 3, 2]])

In [43]:
# 5. For a given 2-D array, perform addition and subtraction on the given matrices
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]])
np.add(a,b)
np.subtract(a,b)

array([[-4, -4],
       [-4, -4]])

In [44]:
# 6. Matrix multiplication for 1-D array.
a = np.array([9, 5, 7, 4])
b = np.array([9, 5, 4, 3])
np.dot(a,b)

146

In [45]:
# 7. Matrix multiplication for 2-D array.
a = np.array([[1, 0],
             [0, 1]])

b = np.array([[4, 1],
              [2, 2]])
np.dot(a,b)

array([[4, 1],
       [2, 2]])

In [46]:
"""
8. Solve the below equations using numpy solver
4X+3Y+2Z = 25,

-2X+2Y+3Z = -10,

3X-5Y+2Z = -4
"""
a = np.array([[4, 3, 2], [-2, 2, 3], [3, -5, 2]])
b = np.array([25, -10, -4])
np.linalg.solve(a, b)

array([ 5.,  3., -2.])

In [47]:
# 9. For a given array, compute ex element-wise
a = np.array([3, 4, 6, 9, 8])
np.exp(a)

array([  20.08553692,   54.59815003,  403.42879349, 8103.08392758,
       2980.95798704])

In [48]:
# 10. For a given array, find the cumulative sum of the elements row wise and column wise
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
np.cumsum(a,axis=0)
np.cumsum(a,axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])